name: APTOS 2019 Blindness Detection
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy=1.16.4
  - scikit-image
  - scikit-learn
  - pip
  - pip:
    - tensorflow==1.13.1
    - imgaug==0.2.9
    - opencv_python==4.1.1.26
    - numpy==1.16.4
    - pandas==0.24.2
    - Keras==2.2.4
    - mlflow==1.0.0
    - matplotlib==3.1.1
    - tqdm==4.35.0
    - scikit_image==0.15.0
    - Pillow==6.1.0
    - scikit_learn==0.21.3